upgrade some deps, test only with Julia 1.3
hopefully fixes Travis test failures:

ERROR: LoadError: LoadError: InitError: error compiling __init__: could not load library "/home/travis/.julia/packages/ImageMagick/vMfoS/deps/usr/lib/libMagickWand-6.Q16.so"
/lib/x86_64-linux-gnu/libz.so.1: version `ZLIB_1.2.9' not found (required by /home/travis/.julia/packages/ImageMagick/vMfoS/deps/usr/lib/libpng16.so.16)